name: aiml25-ma1
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10  # Ensure compatibility with PyTorch MPS
  - pip  # Needed to install PyTorch manually
  - imageio=2.36.1
  - ipykernel=6.29.5
  - matplotlib=3.10.0
  - numpy<2.0  # Ensure compatibility with PyTorch
  - ipywidgets=8.1.5
  - tqdm=4.67.1
  - scikit-learn=1.6.0
  - pip:
      - numpy<2.0  # Explicitly install compatible NumPy via pip
      - torch
      - torchvision
      - torchaudio
      - --index-url https://download.pytorch.org/whl/cpu  # Specify PyTorch's source
